# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('slug_cs', models.SlugField(null=True)),
                ('slug_en', models.SlugField(null=True)),
                ('content', models.TextField()),
                ('content_cs', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
            ],
        ),
    ]
