# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170813_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
