# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_page_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='page',
            name='slug_cs',
        ),
        migrations.RemoveField(
            model_name='page',
            name='slug_en',
        ),
        migrations.AlterField(
            model_name='page',
            name='active',
            field=models.BooleanField(default=False, help_text="Non active pages won't be shown", verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_cs',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='dynamic',
            field=models.BooleanField(default=True, help_text='Non-dynamic pages does not provide content from database storage, but have a static template instead', verbose_name='Dynamic'),
        ),
        migrations.AlterField(
            model_name='page',
            name='identifier',
            field=models.CharField(help_text='Unique page identifier. Used if target page is going to be static for template loading and other unique situtations', max_length=50, verbose_name='Identifier'),
        ),
    ]
