# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20170820_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='dynamic',
        ),
        migrations.AddField(
            model_name='page',
            name='dynamic_content',
            field=models.BooleanField(default=True, help_text='Determines, whether the page is loaded from a database storage or from a static template', verbose_name='Dynamic content'),
        ),
        migrations.AddField(
            model_name='page',
            name='dynamic_handling',
            field=models.BooleanField(default=False, help_text='Determines, whether the page owns a self handling action method', verbose_name='Dynamic handling'),
        ),
        migrations.AddField(
            model_name='page',
            name='template_path',
            field=models.CharField(help_text='Template path for static handled pages', max_length=155, null=True, verbose_name='Template path'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(help_text='Template content. Django template syntax is supported', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_cs',
            field=models.TextField(help_text='Template content. Django template syntax is supported', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_en',
            field=models.TextField(help_text='Template content. Django template syntax is supported', null=True, verbose_name='Content'),
        ),
    ]
