# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20170820_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Stránka', 'verbose_name_plural': 'Stránky'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='active',
        ),
        migrations.AddField(
            model_name='page',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Neaktivní stránky nebudou zobrazeny', verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(help_text='Template content. Django template syntax is supported', null=True, verbose_name='Obsah'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_cs',
            field=models.TextField(help_text='Template content. Django template syntax is supported', null=True, verbose_name='Obsah'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_en',
            field=models.TextField(help_text='Template content. Django template syntax is supported', null=True, verbose_name='Obsah'),
        ),
        migrations.AlterField(
            model_name='page',
            name='identifier',
            field=models.CharField(help_text='Unique page identifier. Used if target page is going to be static for template loading and other unique situtations', max_length=50, verbose_name='identifikátor'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template_path',
            field=models.CharField(help_text='Template path for static handled pages', max_length=155, null=True, verbose_name='Cesta k šabloně'),
        ),
    ]
