# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20170826_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Slug used in URL. Leave blank if creating a parent entry containing multiple other entries', verbose_name='Slug')),
                ('slug_cs', models.SlugField(help_text='Slug used in URL. Leave blank if creating a parent entry containing multiple other entries', null=True, verbose_name='Slug')),
                ('slug_en', models.SlugField(help_text='Slug used in URL. Leave blank if creating a parent entry containing multiple other entries', null=True, verbose_name='Slug')),
                ('position', models.PositiveIntegerField(help_text='Determines in which order should the entries be drawn', verbose_name='Position')),
                ('enabled', models.BooleanField(default=False, help_text="Disabled entities aren't publicaly available", verbose_name='Enabled')),
                ('parent', models.ForeignKey(help_text='Parent menu entry (nested list -> eg. dropdown menu)', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.MenuEntry')),
            ],
            options={
                'verbose_name': 'Menu entry',
                'verbose_name_plural': 'Menu entries',
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='enabled',
            field=models.BooleanField(default=False, help_text="Disabled entities aren't publicaly available", verbose_name='Enabled'),
        ),
    ]
