# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20170826_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='menu_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.MenuEntry'),
        ),
    ]
